#!/usr/bin/env python3
# Copyright (C) 2026 Marcel Verpaalen
# SPDX-License-Identifier: GPL-3.0-or-later
# Licensed under the GNU General Public License v3.0 or later.
"""
Source collector: Copernicus Marine (CMEMS) IBI Surface Currents (catalog only).

Outputs a GRIB2 source entry pointing to the rolling GitHub Release where
the actual GRIB2 files are hosted (generated by generate_ibi_gribs.py).
This collector uses only stdlib; it does NOT generate GRIB2 files or
contact the Copernicus Marine service.

This module is also the single source of truth for the CMEMS IBI region
metadata (REGIONS below): generate_ibi_gribs.py imports it directly (via
sys.path, since it lives in a sibling directory) rather than keeping a
second, drifting copy — same convention as sources/nos_ofs.py.

Issue #3: two candidate European high-resolution sources were investigated
live on 2026-07-23 — CMEMS IBI (this module) and CESGA/MeteoGalicia THREDDS
(mandeo.meteogalicia.es), which was unreachable (502 — the site's own Apache
proxy failing DNS lookup for its backend, a genuine outage on their end) and
is deferred to a separate follow-up.

Region bounds were chosen to keep native-resolution (~0.0278 deg / 3 km)
point counts modest — no block-pooling needed, unlike the NOS OFS pipeline
(see generate_ibi_gribs.py) — and cross-validated against an independent
regional model (CESGA Atlantic 2, via signalk-tidal-currents' nvchart
downloader) at 8 points x 5 hours in the Galicia region: median speed
difference +0.004 m/s, median direction difference -8.3 deg where both
models showed a non-trivial current. The one systematic disagreement was a
single near-shore point (Ria de Vigo mouth) that CESGA's coastline treats
as wet and IBI's treats as land — an expected difference between two
independently-run models' coastline masks, not a data quality issue with
either.

Issue #3 follow-up (2026-07-23): expanded south along the same coast with
ibi_portugal and ibi_gulf_of_cadiz. The underlying IBI dataset's real extent
is 26.17-56.08N / 19.08W-5.08E (confirmed live via `copernicusmarine
describe` and a data probe, not just the product page — the product page's
bare "5.08" reads like it could be 5.08W but is genuinely 5.08E: IBI's grid
has non-trivial wet-cell data as far as the Balearic longitude, an open-
boundary artifact of the model, not something we rely on here). These two
new regions cover Portugal and the Gulf of Cadiz/Gibraltar Strait, well
inside that box.

Sizing: each new region's valid (wet) point count was measured with a live
single-timestep probe against the real dataset, then scaled by the
bytes/wet-point/hour rate back-calculated from the two existing regions'
actual release file sizes (~6.4-6.9 bytes/wet-point/hour, consistent
between them) to predict the 72h file size before committing to a bbox —
same reasoning as the NOS OFS pooling decisions, adapted for a dataset that
doesn't need pooling. ibi_portugal and ibi_gulf_of_cadiz are separate
regions rather than one combined box for the same modularity reason
galicia/biscay are separate: independently sized (~2.1 MB / ~0.9 MB)
downloads a sailor can pick between, not a single ~4 MB Iberia-wide file
covering areas most users only sail a fraction of. They overlap
ibi_galicia and each other by ~0.2-0.5 deg at their shared edges so a
route crossing a seam never falls into a gap.

Deliberately NOT extended into ibi_biscay's latitude range (47N+) even
though NWS's future box will start at 46N — that 1 degree of overlap
between ibi_biscay's existing north edge and NWS's south edge is enough to
avoid a seam gap without this repo maintaining two regional models over
the same stretch of French coast.
"""

import json
import sys

# Gate for the catalog entry, same convention as nos_ofs.PUBLISH_TO_CATALOG:
# the GRIB2 pipeline can run and upload release assets independently of
# whether the source is advertised in tide-current-index.json.
PUBLISH_TO_CATALOG = True

GITHUB_RELEASE_BASE = "https://github.com/marcelrv/signalk-router-data/releases/download/ibi-currents-latest"

DATASET_ID = "cmems_mod_ibi_phy_anfc_0.027deg-2D_PT1H-m"

# forecast_hours: capped well below the ~216 h the anfc dataset actually
# offers (same rationale as the NOS OFS models capping below their native
# horizon — keeps file size and relevance to near-term routing reasonable).
# target_res_deg: native resolution (~0.0278 deg) — regions are sized to
# keep native point counts modest rather than pooling, unlike NOS OFS.
REGIONS = {
    "ibi_galicia": {
        "name": "NW Iberia / Galicia (Rias Baixas)",
        "description": "Surface current forecasts for the Galician coast and Rias Baixas "
                       "(NW Spain).",
        "bounds": {"min_lat": 41.5, "max_lat": 43.7, "min_lon": -9.5, "max_lon": -8.0},
        "target_res_deg": 0.0278,
        "forecast_hours": 72,
    },
    "ibi_biscay": {
        "name": "Bay of Biscay",
        "description": "Surface current forecasts for the Bay of Biscay, from the French "
                       "Atlantic coast down through the Spanish Cantabrian coast "
                       "(Bilbao/San Sebastian).",
        "bounds": {"min_lat": 43.0, "max_lat": 47.0, "min_lon": -4.5, "max_lon": -1.0},
        "target_res_deg": 0.0278,
        "forecast_hours": 72,
    },
    "ibi_portugal": {
        "name": "Portugal (Atlantic Coast & Algarve)",
        "description": "Surface current forecasts for mainland Portugal, from the Minho/Galicia "
                       "border down through Porto, Lisbon and the Algarve.",
        # Overlaps ibi_galicia by 0.2 deg (41.5-41.7N) so a route crossing the
        # Minho border doesn't fall into a seam gap. Measured 4443 wet points
        # live -> ~2.1 MB at 72h, in between the two existing regions' sizes.
        "bounds": {"min_lat": 36.9, "max_lat": 41.7, "min_lon": -9.6, "max_lon": -6.7},
        "target_res_deg": 0.0278,
        "forecast_hours": 72,
    },
    "ibi_gulf_of_cadiz": {
        "name": "Gulf of Cadiz & Gibraltar Strait",
        "description": "Surface current forecasts for the Gulf of Cadiz (Huelva, Cadiz) and the "
                       "Strait of Gibraltar approach.",
        # Overlaps ibi_portugal's SE corner (~-7.6..-6.7 lon, 36.9-37.3 lat) —
        # deliberate, same seam-safety reasoning. min_lat dips to 35.75 to
        # keep the full width of the Strait (both shores) in one region,
        # since current through the Strait matters for anyone transiting it.
        # Measured 1942 wet points live -> ~0.9 MB at 72h.
        "bounds": {"min_lat": 35.75, "max_lat": 37.3, "min_lon": -7.6, "max_lon": -5.3},
        "target_res_deg": 0.0278,
        "forecast_hours": 72,
    },
}


def _polygon_from_bounds(b: dict) -> dict:
    return {"type": "Polygon", "coordinates": [[
        [b["min_lon"], b["min_lat"]], [b["max_lon"], b["min_lat"]],
        [b["max_lon"], b["max_lat"]], [b["min_lon"], b["max_lat"]],
        [b["min_lon"], b["min_lat"]],
    ]]}


def _bbox_of_polygons(poly_coords: list) -> dict:
    lons = [pt[0] for poly in poly_coords for ring in poly for pt in ring]
    lats = [pt[1] for poly in poly_coords for ring in poly for pt in ring]
    return {"min_lat": min(lats) if lats else 0, "min_lon": min(lons) if lons else 0,
            "max_lat": max(lats) if lats else 0, "max_lon": max(lons) if lons else 0}


def main() -> None:
    if not PUBLISH_TO_CATALOG:
        json.dump([], sys.stdout)
        print()
        return

    all_poly_coords = []
    files_entries = []

    for rid, r in REGIONS.items():
        b = r["bounds"]
        poly = _polygon_from_bounds(b)
        all_poly_coords.append(poly["coordinates"])
        files_entries.append({
            "region_id": rid,
            "name": r["name"],
            "description": r["description"],
            "boundary_geometry": poly,
            "type": "forecast",
            "url_template": f"{GITHUB_RELEASE_BASE}/{rid}_currents.grb2",
            # Single multi-message file per region (every forecast hour
            # bundled as separate GRIB2 messages) — a single-element array
            # signals "one file, not one per hour" (see
            # specs/tide-current-catalog.md §3.3 and the NOS OFS entries in
            # nos_ofs.py for the same convention).
            "forecast_hours": [0],
            # IBI's anfc dataset updates once/day (~14:00 UTC) — a single
            # cycle, unlike NOS OFS's multiple daily cycles.
            "cycle_hours": ["15"],
        })

    source = {
        "id": "cmems_ibi",
        "source": "copernicus",
        "type": "grib2",
        "name": "Surface Current Forecasts — Iberia/Biscay/Gibraltar (Copernicus Marine CMEMS IBI)",
        # Attribution wording follows the Copernicus Marine license's
        # required format for a "Value Added Product" / "Derivative Work"
        # (section 2.4(a) — applies here because the data is reformatted
        # netCDF->GRIB2 and geographically subset, not redistributed
        # unmodified): "Generated using E.U. Copernicus Marine Service
        # Information" plus the product's DOI. Verified live 2026-07-23
        # against https://marine.copernicus.eu/user-corner/service-commitments-and-licence
        # and the product page's DOI link.
        "description": "Gridded surface current forecasts (tidal + weather + river forcing) for "
                       "the NE Atlantic / Bay of Biscay / Iberian Peninsula, extracted from the "
                       "Copernicus Marine Service IBI analysis-and-forecast model and re-encoded "
                       "as compact GRIB2 by signalk-router-data scripts "
                       "(https://github.com/marcelrv/signalk-router-data). Generated using E.U. "
                       "Copernicus Marine Service Information (https://doi.org/10.48670/moi-00027); "
                       "this repackaging is NOT an official Copernicus product and is not endorsed "
                       "by Mercator Ocean International.",
        "contributor": "Copernicus Marine Service / Mercator Ocean International",
        "url": "https://data.marine.copernicus.eu/product/IBI_ANALYSISFORECAST_PHY_005_001/description",
        "tags": ["grib2", "regional", "gridded", "forecast", "copernicus", "cmems",
                 "ocean-currents", "daily", "europe"],
        "region": {
            "name": "NE Atlantic — Bay of Biscay, Iberian Peninsula, Gibraltar Strait",
            "bounding_box": _bbox_of_polygons(all_poly_coords) if all_poly_coords else {},
            "boundary_geometry": {"type": "MultiPolygon", "coordinates": all_poly_coords},
        },
        "update_check": {"method": "expiry", "max_age_hours": 24, "last_checked": ""},
        "files": files_entries,
    }

    json.dump(source, sys.stdout, indent=2)
    print()


if __name__ == "__main__":
    main()
