#!/usr/bin/env python3
# Copyright (C) 2026 Marcel Verpaalen
# SPDX-License-Identifier: GPL-3.0-or-later
# Licensed under the GNU General Public License v3.0 or later.
"""
Source collector: Copernicus Marine (CMEMS) Mediterranean Surface Currents
(catalog only).

Outputs a GRIB2 source entry pointing to the rolling GitHub Release where
the actual GRIB2 files are hosted (generated by generate_med_gribs.py).
This collector uses only stdlib; it does NOT generate GRIB2 files or
contact the Copernicus Marine service.

This module is also the single source of truth for the CMEMS MED region
metadata (REGIONS below): generate_med_gribs.py imports it directly (via
sys.path, since it lives in a sibling directory) rather than keeping a
second, drifting copy — same convention as sources/cmems_ibi.py and
sources/cmems_nws.py.

Issue #7: Mediterranean Sea Physics Analysis and Forecast
(MEDSEA_ANALYSISFORECAST_PHY_006_013, produced by CMCC, Italy). Confirmed
live via `copernicusmarine describe -p MEDSEA_ANALYSISFORECAST_PHY_006_013`:
the hourly-mean surface-current dataset
(cmems_mod_med_phy-cur_anfc_4.2km-2D_PT1H-m) is, like IBI and NWS, a plain
regular lat/lon grid (1-D lat/lon coordinates, uniform step) spanning
30.19-45.98N / 17.29W-36.29E at ~4.2 km native resolution (0.04167 deg,
square — unlike NWS's non-square step) — so the same simple non-pooled
pipeline as generate_ibi_gribs.py/generate_nws_gribs.py applies. The domain
dips west of Gibraltar into the Atlantic for the same open-boundary reason
IBI dips east into the Alboran Sea (see cmems_ibi.py's docstring) — regions
here start at the Strait itself and let IBI's ibi_gulf_of_cadiz own the
Atlantic side, same non-duplication call already made at the Biscay/NWS
seam.

License: same catalog-wide Copernicus Marine Service Licence as IBI/NWS
(verified against https://marine.copernicus.eu/user-corner/service-
commitments-and-licence — free access, and Value Added Products /
Derivative Work explicitly permitted "for any purpose", no per-product
carve-outs). Producer is CMCC (Italy); DOI is 10.48670/mds-00359 — a
different prefix ("mds" vs IBI/NWS's "moi") than the other Copernicus
Marine sources in this repo, confirmed straight from
`copernicusmarine describe`'s own `digital_object_identifier` field (not
just the product page) specifically because that looked enough like a
typo to double-check rather than assume either way.

Resolution works in this repo's favor here: 4.2 km is actually the
*coarsest* of the three CMEMS products in this catalog (~4.2x fewer
points/deg^2 than NWS, ~2.25x fewer than IBI), which matters given how
much larger the Mediterranean basin is than any single NWS region. All 10
regions below were probed live and came in at 1.2-7.2 MB at 72h on the
first attempt — no oversized-region rework needed, unlike the NWS 5->11
region split.

Two seam gaps were caught during the adjacency review (same review that
caught NWS's St George's Channel gap) and fixed before this was ever
generated for real, not after:
  - med_alboran and med_balearics_costa were only touching (not
    overlapping) around Almeria/Cartagena — fixed by extending
    med_balearics_costa's south/west edges (36.8/-1.3 instead of 37.5/-1.0).
  - med_ionian and med_aegean touched exactly at 22.0E near Cape Malea/
    Kythira — fixed by extending med_ionian east to 22.3 and med_aegean
    west to 21.8.
med_alboran also overlaps IBI's ibi_gulf_of_cadiz (-7.6..-5.3E,
35.75-37.3N) by 0.2 deg (lon) / 1.25 deg (lat), so the Gibraltar Strait
transit itself has no seam gap between the two products.

Deliberately stops at 34.0N on the Turkey/Eastern-Med region rather than
reaching the Levant (Israel/Lebanon/Egypt, mostly south of 34N) — this
repo's European-waters framing (see issue #3's original scoping) puts the
Levant coast out of scope for now, not a sizing constraint.

    region                  72h size (measured, real generate_med_gribs.py run)
    med_alboran             1.18 MB
    med_balearics_costa     5.75 MB
    med_gulf_lion           3.87 MB
    med_liguria_nw_italy    1.33 MB
    med_tyrrhenian          6.57 MB
    med_sicily_malta        3.39 MB
    med_adriatic            5.83 MB
    med_ionian              5.38 MB
    med_aegean              6.80 MB
    med_turkey_east         6.99 MB
"""

import json
import sys

# Gate for the catalog entry, same convention as cmems_ibi.PUBLISH_TO_CATALOG.
PUBLISH_TO_CATALOG = True

GITHUB_RELEASE_BASE = "https://github.com/marcelrv/signalk-router-data/releases/download/med-currents-latest"

DATASET_ID = "cmems_mod_med_phy-cur_anfc_4.2km-2D_PT1H-m"

# target_res_deg: native resolution, square (see module docstring) —
# regions sized to keep native point counts modest rather than pooling,
# same choice as CMEMS IBI/NWS.
REGIONS = {
    "med_alboran": {
        "name": "Alboran Sea & Costa del Sol",
        "description": "Surface current forecasts for the Alboran Sea, from the Strait of "
                       "Gibraltar through the Costa del Sol to Almeria.",
        "bounds": {"min_lat": 35.7, "max_lat": 37.0, "min_lon": -5.5, "max_lon": -1.0},
        "target_res_deg": 0.04166667002172143,
        "forecast_hours": 72,
    },
    "med_balearics_costa": {
        "name": "Balearics, Costa Blanca & Costa Brava",
        "description": "Surface current forecasts for Spain's Mediterranean coast (Cartagena "
                       "to the French border) and the Balearic Islands.",
        "bounds": {"min_lat": 36.8, "max_lat": 42.5, "min_lon": -1.3, "max_lon": 4.5},
        "target_res_deg": 0.04166667002172143,
        "forecast_hours": 72,
    },
    "med_gulf_lion": {
        "name": "Gulf of Lion & French Riviera",
        "description": "Surface current forecasts for the Gulf of Lion and the French "
                       "Riviera, from the Spanish border to Monaco.",
        "bounds": {"min_lat": 41.0, "max_lat": 44.0, "min_lon": 3.0, "max_lon": 9.5},
        "target_res_deg": 0.04166667002172143,
        "forecast_hours": 72,
    },
    "med_liguria_nw_italy": {
        "name": "Liguria & NW Italy",
        "description": "Surface current forecasts for the Ligurian coast, from Genoa "
                       "through the Cinque Terre to Tuscany.",
        "bounds": {"min_lat": 42.0, "max_lat": 44.5, "min_lon": 8.0, "max_lon": 11.0},
        "target_res_deg": 0.04166667002172143,
        "forecast_hours": 72,
    },
    "med_tyrrhenian": {
        "name": "Tyrrhenian Sea (Sardinia, Corsica & Naples)",
        "description": "Surface current forecasts for the Tyrrhenian Sea — Sardinia, "
                       "Corsica's east coast, Rome/Civitavecchia and Naples.",
        "bounds": {"min_lat": 38.0, "max_lat": 43.0, "min_lon": 8.0, "max_lon": 15.0},
        "target_res_deg": 0.04166667002172143,
        "forecast_hours": 72,
    },
    "med_sicily_malta": {
        "name": "Sicily & Malta",
        "description": "Surface current forecasts for Sicily, Malta and the Sicilian "
                       "Channel.",
        "bounds": {"min_lat": 35.5, "max_lat": 38.5, "min_lon": 10.5, "max_lon": 16.0},
        "target_res_deg": 0.04166667002172143,
        "forecast_hours": 72,
    },
    "med_adriatic": {
        "name": "Adriatic Sea",
        "description": "Surface current forecasts for the Adriatic Sea — Croatia, "
                       "Montenegro, Albania, and Italy's east coast up to Venice.",
        "bounds": {"min_lat": 39.5, "max_lat": 45.9, "min_lon": 12.0, "max_lon": 20.0},
        "target_res_deg": 0.04166667002172143,
        "forecast_hours": 72,
    },
    "med_ionian": {
        "name": "Ionian Sea (Western Greece & Puglia)",
        "description": "Surface current forecasts for the Ionian Sea — western Greece "
                       "(Corfu, Zakynthos) and Italy's Puglia/heel.",
        "bounds": {"min_lat": 36.0, "max_lat": 40.0, "min_lon": 15.5, "max_lon": 22.3},
        "target_res_deg": 0.04166667002172143,
        "forecast_hours": 72,
    },
    "med_aegean": {
        "name": "Aegean Sea",
        "description": "Surface current forecasts for the Aegean Sea — the Cyclades, "
                       "Dodecanese, Crete and Athens.",
        "bounds": {"min_lat": 34.5, "max_lat": 41.0, "min_lon": 21.8, "max_lon": 28.5},
        "target_res_deg": 0.04166667002172143,
        "forecast_hours": 72,
    },
    "med_turkey_east": {
        "name": "Turkish Coast & Eastern Mediterranean",
        "description": "Surface current forecasts for the Turkish Aegean/Mediterranean "
                       "coast and Cyprus.",
        "bounds": {"min_lat": 34.0, "max_lat": 40.5, "min_lon": 26.0, "max_lon": 36.2},
        "target_res_deg": 0.04166667002172143,
        "forecast_hours": 72,
    },
}


def _polygon_from_bounds(b: dict) -> dict:
    return {"type": "Polygon", "coordinates": [[
        [b["min_lon"], b["min_lat"]], [b["max_lon"], b["min_lat"]],
        [b["max_lon"], b["max_lat"]], [b["min_lon"], b["max_lat"]],
        [b["min_lon"], b["min_lat"]],
    ]]}


def _bbox_of_polygons(poly_coords: list) -> dict:
    lons = [pt[0] for poly in poly_coords for ring in poly for pt in ring]
    lats = [pt[1] for poly in poly_coords for ring in poly for pt in ring]
    return {"min_lat": min(lats) if lats else 0, "min_lon": min(lons) if lons else 0,
            "max_lat": max(lats) if lats else 0, "max_lon": max(lons) if lons else 0}


def main() -> None:
    if not PUBLISH_TO_CATALOG:
        json.dump([], sys.stdout)
        print()
        return

    all_poly_coords = []
    files_entries = []

    for rid, r in REGIONS.items():
        b = r["bounds"]
        poly = _polygon_from_bounds(b)
        all_poly_coords.append(poly["coordinates"])
        files_entries.append({
            "region_id": rid,
            "name": r["name"],
            "description": r["description"],
            "boundary_geometry": poly,
            "type": "forecast",
            "url_template": f"{GITHUB_RELEASE_BASE}/{rid}_currents.grb2",
            # Single multi-message file per region — see cmems_ibi.py's
            # identical convention for why this is [0], not one per hour.
            "forecast_hours": [0],
            # MedSea updates daily at 16:00 UTC — same +1h publish-lag
            # buffer convention as cmems_ibi.py/cmems_nws.py's cycle_hours.
            "cycle_hours": ["17"],
        })

    source = {
        "id": "cmems_med",
        "source": "copernicus",
        "type": "grib2",
        "name": "Surface Current Forecasts — Mediterranean Sea (Copernicus Marine CMEMS MED)",
        # Attribution wording follows the same Copernicus Marine license
        # clause as cmems_ibi.py/cmems_nws.py (section 2.4(a), Value Added
        # Product / Derivative Work), just with MED's own producer and DOI.
        # Verified live 2026-07-23 against https://marine.copernicus.eu/
        # user-corner/service-commitments-and-licence and, for the DOI
        # specifically, `copernicusmarine describe`'s own metadata rather
        # than just the product page (see module docstring).
        "description": "Gridded surface current forecasts (tidal + weather forcing) for the "
                       "Mediterranean Sea, extracted from the Copernicus Marine Service MED "
                       "analysis-and-forecast model and re-encoded as compact GRIB2 by "
                       "signalk-router-data scripts (https://github.com/marcelrv/"
                       "signalk-router-data). Generated using E.U. Copernicus Marine Service "
                       "Information (https://doi.org/10.48670/mds-00359); this repackaging is "
                       "NOT an official Copernicus product and is not endorsed by CMCC or "
                       "Mercator Ocean International.",
        "contributor": "Copernicus Marine Service / CMCC (Italy)",
        "url": "https://data.marine.copernicus.eu/product/MEDSEA_ANALYSISFORECAST_PHY_006_013/description",
        "tags": ["grib2", "regional", "gridded", "forecast", "copernicus", "cmems",
                 "ocean-currents", "daily", "mediterranean", "europe"],
        "region": {
            "name": "Mediterranean Sea",
            "bounding_box": _bbox_of_polygons(all_poly_coords) if all_poly_coords else {},
            "boundary_geometry": {"type": "MultiPolygon", "coordinates": all_poly_coords},
        },
        "update_check": {"method": "expiry", "max_age_hours": 24, "last_checked": ""},
        "files": files_entries,
    }

    json.dump(source, sys.stdout, indent=2)
    print()


if __name__ == "__main__":
    main()
