#!/usr/bin/env python3
# Copyright (C) 2026 Marcel Verpaalen
# SPDX-License-Identifier: GPL-3.0-or-later
# Licensed under the GNU General Public License v3.0 or later.
"""
Source collector: Copernicus Marine (CMEMS) NWS Surface Currents (catalog only).

Outputs a GRIB2 source entry pointing to the rolling GitHub Release where
the actual GRIB2 files are hosted (generated by generate_nws_gribs.py).
This collector uses only stdlib; it does NOT generate GRIB2 files or
contact the Copernicus Marine service.

This module is also the single source of truth for the CMEMS NWS region
metadata (REGIONS below): generate_nws_gribs.py imports it directly (via
sys.path, since it lives in a sibling directory) rather than keeping a
second, drifting copy — same convention as sources/cmems_ibi.py.

Issue #3 follow-up (2026-07-23): NWS (Atlantic - European North West Shelf,
NWSHELF_ANALYSISFORECAST_PHY_004_013, produced by the UK Met Office as
NWS-MFC) fills the coverage gap between CMEMS IBI (Bay of Biscay north
edge at 47N) and the North Sea/Baltic (BSH). Confirmed live via
`copernicusmarine describe -p NWSHELF_ANALYSISFORECAST_PHY_004_013`: the
hourly-instantaneous surface-current dataset
(cmems_mod_nws_phy-cur_anfc_1.5km-2D_PT1H-i) is, like IBI, a plain regular
lat/lon grid (1-D lat/lon coordinates, uniform step) spanning
46.0-62.74N / 16.0W-13.0E at ~1.5 km native resolution (lat step 0.01351
deg, lon step 0.03030 deg — non-square because NWS is at higher latitude
than IBI, so a degree of longitude is physically shorter) — so the same
simple non-pooled pipeline as generate_ibi_gribs.py applies, just with
per-axis increments instead of one shared value.

License: same catalog-wide Copernicus Marine Service Licence as IBI
(verified against https://marine.copernicus.eu/user-corner/service-
commitments-and-licence — free access, and Value Added Products /
Derivative Work explicitly permitted "for any purpose", no per-product
carve-outs). Attribution differs only in producer name and DOI: NWS is
produced by the Met Office (UK) / NWS-MFC, not Mercator Ocean, and its DOI
is 10.48670/moi-00054 (vs IBI's moi-00027).

Whole-domain size at 1.5 km would be ~1.19M grid points/timestep (1240 x
958) — far too large for one file, so this is split into cruising-ground
regions rather than one shelf-wide box, same reasoning as ibi_portugal /
ibi_gulf_of_cadiz being split from a single Iberia-south box.

First pass at this used 5 large regions (whole Channel, whole Irish Sea,
whole west Scotland, whole SW Ireland, whole UK east coast) sized only by
area. Measuring them for real showed the two biggest — a single English
Channel box and a single UK-east-coast box — came out at 13.9 MB and
27.1 MB, well above this repo's existing largest file
(NOS OFS's sscofs at 9.76 MB, per the ofs-currents-latest release) because
NWS's ~1.5 km resolution packs roughly the same bytes/wet-point/hour rate
as IBI (~6.4-6.9) into a much denser grid per unit area. Split into the 11
regions below instead, each independently probed and generated for real;
all land in the 2.7-10.9 MB range, in line with the rest of the repo:

    region                72h size (measured, real generate_nws_gribs.py run)
    nws_west_channel        6.19 MB
    nws_solent              2.76 MB
    nws_dover_strait        3.50 MB
    nws_irish_sea          10.32 MB
    nws_ireland_south       6.67 MB
    nws_ireland_north       5.97 MB
    nws_scotland_clyde      5.29 MB
    nws_scotland_north      7.17 MB
    nws_uk_thames           2.85 MB
    nws_uk_ne_england       3.68 MB
    nws_uk_scotland_e       9.00 MB

Every shared edge between neighboring regions overlaps by ~0.2-0.6 deg
(not just touches) so a route crossing a seam never falls into a gap —
same convention as the IBI regions. One gap this caught during review:
an initial cut had the Irish Sea box's west edge (-6.5) and the SW-Ireland
box's east edge (-7.3) merely adjacent with numbers that looked like they
overlapped but didn't (-7.3 is west of -6.5, leaving St George's Channel —
the Ireland-Wales route — uncovered). Fixed by extending both Ireland
regions' east edge to -6.3.

Follow-up (2026-07-23): added nws_orkney_shetland to close the
Orkney/Shetland/Pentland Firth gap noted above. Tried widening
nws_scotland_north or nws_uk_scotland_e to swallow it first — both blew
back up to the same size class the 11-way split was built to avoid
(27.7 MB and 22.8 MB respectively, measured), for the same reason: NWS's
point density means "just extend the bbox a bit" is never free. A
standalone region measured at 10.6 MB instead (real generate_nws_gribs.py
run) — close to nws_irish_sea's 10.3 MB, and correct on its own terms
(Shetland is a genuinely separate cruising ground from both mainland NW
Scotland and the Firth of Forth, not a natural extension of either file).
Overlaps nws_scotland_north by 0.2 deg (lon) / 1.2 deg (lat) and
nws_uk_scotland_e by 2.0 deg (lon) / 0.7 deg (lat).

Norway remains out of scope — outside NWS's domain entirely (max 62.74N
only reaches southern Norway at the very edge, and even that edge isn't
requested here). nws_uk_scotland_e/nws_uk_ne_england's west edge
(-2.2/-2.5) overlaps BSH's North Sea coarse grid (starts -3.92E) with a
wide margin, so there's no seam gap against BSH.
"""

import json
import sys

# Gate for the catalog entry, same convention as cmems_ibi.PUBLISH_TO_CATALOG.
PUBLISH_TO_CATALOG = True

GITHUB_RELEASE_BASE = "https://github.com/marcelrv/signalk-router-data/releases/download/nws-currents-latest"

DATASET_ID = "cmems_mod_nws_phy-cur_anfc_1.5km-2D_PT1H-i"

# target_res_lat_deg / target_res_lon_deg: native resolution, non-square
# (see module docstring) — regions are sized to keep native point counts
# modest rather than pooling, same choice as CMEMS IBI.
REGIONS = {
    "nws_west_channel": {
        "name": "Western Channel & Scillies",
        "description": "Surface current forecasts for the western English Channel, from "
                       "Ushant/Brest and the Isles of Scilly through Plymouth and Falmouth.",
        "bounds": {"min_lat": 48.3, "max_lat": 51.3, "min_lon": -5.5, "max_lon": -2.8},
        "target_res_lat_deg": 0.013513511183571681,
        "target_res_lon_deg": 0.030303030303030304,
        "forecast_hours": 72,
    },
    "nws_solent": {
        "name": "Solent & Central Channel",
        "description": "Surface current forecasts for the Solent, Poole, Portland, Cherbourg "
                       "and the Channel Islands.",
        "bounds": {"min_lat": 49.5, "max_lat": 51.3, "min_lon": -3.0, "max_lon": -0.8},
        "target_res_lat_deg": 0.013513511183571681,
        "target_res_lon_deg": 0.030303030303030304,
        "forecast_hours": 72,
    },
    "nws_dover_strait": {
        "name": "Dover Strait & Eastern Channel",
        "description": "Surface current forecasts for the eastern English Channel and Dover "
                       "Strait, from Brighton and Boulogne to Calais and Dover.",
        "bounds": {"min_lat": 49.5, "max_lat": 51.3, "min_lon": -1.0, "max_lon": 2.0},
        "target_res_lat_deg": 0.013513511183571681,
        "target_res_lon_deg": 0.030303030303030304,
        "forecast_hours": 72,
    },
    "nws_irish_sea": {
        "name": "Irish Sea, Bristol Channel & North Channel",
        "description": "Surface current forecasts for the Irish Sea, Bristol Channel, Wales, "
                       "the Isle of Man and NW England.",
        "bounds": {"min_lat": 51.1, "max_lat": 55.5, "min_lon": -6.5, "max_lon": -2.5},
        "target_res_lat_deg": 0.013513511183571681,
        "target_res_lon_deg": 0.030303030303030304,
        "forecast_hours": 72,
    },
    "nws_ireland_south": {
        "name": "South Ireland (Cork, Kerry & Shannon)",
        "description": "Surface current forecasts for the south coast of Ireland, from Cork "
                       "and Kinsale through Kerry and the Shannon Estuary.",
        "bounds": {"min_lat": 51.0, "max_lat": 53.2, "min_lon": -11.2, "max_lon": -6.3},
        "target_res_lat_deg": 0.013513511183571681,
        "target_res_lon_deg": 0.030303030303030304,
        "forecast_hours": 72,
    },
    "nws_ireland_north": {
        "name": "West & Northwest Ireland (Galway & Donegal)",
        "description": "Surface current forecasts for the west and northwest coasts of "
                       "Ireland, from Galway Bay through Donegal.",
        "bounds": {"min_lat": 53.2, "max_lat": 55.5, "min_lon": -11.2, "max_lon": -6.3},
        "target_res_lat_deg": 0.013513511183571681,
        "target_res_lon_deg": 0.030303030303030304,
        "forecast_hours": 72,
    },
    "nws_scotland_clyde": {
        "name": "Firth of Clyde & Southern Hebrides",
        "description": "Surface current forecasts for the Firth of Clyde, Kintyre, Islay, "
                       "Jura and the southern Hebrides.",
        "bounds": {"min_lat": 54.9, "max_lat": 57.2, "min_lon": -8.0, "max_lon": -4.3},
        "target_res_lat_deg": 0.013513511183571681,
        "target_res_lon_deg": 0.030303030303030304,
        "forecast_hours": 72,
    },
    "nws_scotland_north": {
        "name": "Northern Hebrides & NW Scotland",
        "description": "Surface current forecasts for the Minches, the northern Hebrides "
                       "(Skye, Lewis, Harris) and the NW Scottish mainland coast.",
        "bounds": {"min_lat": 57.0, "max_lat": 59.5, "min_lon": -8.0, "max_lon": -4.3},
        "target_res_lat_deg": 0.013513511183571681,
        "target_res_lon_deg": 0.030303030303030304,
        "forecast_hours": 72,
    },
    "nws_uk_thames": {
        "name": "Thames Estuary & East Anglia",
        "description": "Surface current forecasts for the Thames Estuary, Kent, Essex and "
                       "East Anglia.",
        "bounds": {"min_lat": 51.0, "max_lat": 53.3, "min_lon": -2.2, "max_lon": 2.2},
        "target_res_lat_deg": 0.013513511183571681,
        "target_res_lon_deg": 0.030303030303030304,
        "forecast_hours": 72,
    },
    "nws_uk_ne_england": {
        "name": "NE England (Humber to Northumberland)",
        "description": "Surface current forecasts for NE England, from the Humber Estuary "
                       "through Yorkshire and Northumberland.",
        "bounds": {"min_lat": 53.1, "max_lat": 56.0, "min_lon": -2.2, "max_lon": 0.3},
        "target_res_lat_deg": 0.013513511183571681,
        "target_res_lon_deg": 0.030303030303030304,
        "forecast_hours": 72,
    },
    "nws_uk_scotland_e": {
        "name": "East Scotland & Firth of Forth",
        "description": "Surface current forecasts for the east coast of Scotland, from the "
                       "Firth of Forth through Aberdeen to the Moray Firth.",
        "bounds": {"min_lat": 55.8, "max_lat": 59.0, "min_lon": -2.5, "max_lon": 0.3},
        "target_res_lat_deg": 0.013513511183571681,
        "target_res_lon_deg": 0.030303030303030304,
        "forecast_hours": 72,
    },
    "nws_orkney_shetland": {
        "name": "Orkney, Shetland & Pentland Firth",
        "description": "Surface current forecasts for Orkney, Shetland, the Pentland Firth "
                       "and the far north Scottish mainland coast.",
        "bounds": {"min_lat": 58.3, "max_lat": 61.0, "min_lon": -4.5, "max_lon": -0.5},
        "target_res_lat_deg": 0.013513511183571681,
        "target_res_lon_deg": 0.030303030303030304,
        "forecast_hours": 72,
    },
}


def _polygon_from_bounds(b: dict) -> dict:
    return {"type": "Polygon", "coordinates": [[
        [b["min_lon"], b["min_lat"]], [b["max_lon"], b["min_lat"]],
        [b["max_lon"], b["max_lat"]], [b["min_lon"], b["max_lat"]],
        [b["min_lon"], b["min_lat"]],
    ]]}


def _bbox_of_polygons(poly_coords: list) -> dict:
    lons = [pt[0] for poly in poly_coords for ring in poly for pt in ring]
    lats = [pt[1] for poly in poly_coords for ring in poly for pt in ring]
    return {"min_lat": min(lats) if lats else 0, "min_lon": min(lons) if lons else 0,
            "max_lat": max(lats) if lats else 0, "max_lon": max(lons) if lons else 0}


def main() -> None:
    if not PUBLISH_TO_CATALOG:
        json.dump([], sys.stdout)
        print()
        return

    all_poly_coords = []
    files_entries = []

    for rid, r in REGIONS.items():
        b = r["bounds"]
        poly = _polygon_from_bounds(b)
        all_poly_coords.append(poly["coordinates"])
        files_entries.append({
            "region_id": rid,
            "name": r["name"],
            "description": r["description"],
            "boundary_geometry": poly,
            "type": "forecast",
            "url_template": f"{GITHUB_RELEASE_BASE}/{rid}_currents.grb2",
            # Single multi-message file per region — see cmems_ibi.py's
            # identical convention for why this is [0], not one per hour.
            "forecast_hours": [0],
            # NWS updates daily at 12:00 UTC — same +1h publish-lag buffer
            # convention as cmems_ibi.py's cycle_hours.
            "cycle_hours": ["13"],
        })

    source = {
        "id": "cmems_nws",
        "source": "copernicus",
        "type": "grib2",
        "name": "Surface Current Forecasts — UK, Ireland & English Channel (Copernicus Marine CMEMS NWS)",
        # Attribution wording follows the same Copernicus Marine license
        # clause as cmems_ibi.py (section 2.4(a), Value Added Product /
        # Derivative Work), just with NWS's own producer and DOI. Verified
        # live 2026-07-23 against https://marine.copernicus.eu/user-corner/
        # service-commitments-and-licence and the NWS product page's DOI.
        "description": "Gridded surface current forecasts (tidal + weather + river forcing) for "
                       "the UK, Ireland and English Channel, extracted from the Copernicus "
                       "Marine Service NWS (North West European Shelf) analysis-and-forecast "
                       "model and re-encoded as compact GRIB2 by signalk-router-data scripts "
                       "(https://github.com/marcelrv/signalk-router-data). Generated using E.U. "
                       "Copernicus Marine Service Information (https://doi.org/10.48670/moi-00054); "
                       "this repackaging is NOT an official Copernicus product and is not endorsed "
                       "by the Met Office or Mercator Ocean International.",
        "contributor": "Copernicus Marine Service / Met Office (UK) / NWS-MFC",
        "url": "https://data.marine.copernicus.eu/product/NWSHELF_ANALYSISFORECAST_PHY_004_013/description",
        "tags": ["grib2", "regional", "gridded", "forecast", "copernicus", "cmems",
                 "ocean-currents", "daily", "europe"],
        "region": {
            "name": "NW European Shelf — UK, Ireland, English Channel",
            "bounding_box": _bbox_of_polygons(all_poly_coords) if all_poly_coords else {},
            "boundary_geometry": {"type": "MultiPolygon", "coordinates": all_poly_coords},
        },
        "update_check": {"method": "expiry", "max_age_hours": 24, "last_checked": ""},
        "files": files_entries,
    }

    json.dump(source, sys.stdout, indent=2)
    print()


if __name__ == "__main__":
    main()
