#!/usr/bin/env python3
# Copyright (C) 2026 Marcel Verpaalen
# SPDX-License-Identifier: GPL-3.0-or-later
# Licensed under the GNU General Public License v3.0 or later.
"""
Source collector: NOAA NOS Operational Forecast Systems (OFS) Surface Currents (catalog only).

Outputs a GRIB2 source entry pointing to the rolling GitHub Release where
the actual GRIB2 files are hosted (generated by generate_ofs_gribs.py).
This collector uses only stdlib; it does NOT generate GRIB2 files or
contact real-time data servers.

This module is also the single source of truth for the NOS OFS model
metadata (MODELS below): generate_ofs_gribs.py imports it directly (via
sys.path, since it lives in a sibling directory) rather than keeping a
second, drifting copy. Keep this module stdlib-only — the weekly index
generator runs it without the heavy netCDF/eccodes dependencies that
generate_ofs_gribs.py requires.

Model cycles, forecast horizons, and bounds below were verified live
against the THREDDS catalog (opendap.co-ops.nos.noaa.gov) on 2026-07-14:
grid corner coordinates were fetched via the DAP .ascii endpoint and
bounds set from them (rounded outward to ~0.1 degree). In particular:
  - SSCOFS = Salish Sea & Columbia River OFS, NOT "Southern California".
    Confirmed grid corners: 44.37N/-129.53E to 52.13N/-121.94E.
  - NGOFS2's grid actually starts near 21.8N (not the previously assumed
    25N). Confirmed grid corners: 21.77N/-97.88E to 30.80N/-85.72E.
  - WCOFS's regulargrid domain spans a much larger area than its name
    suggests (18.42N-55.78N, -145.38E to -112.10E) and is 3-hourly.
"""

import json
import sys

# Gate for the catalog entry (issue #4): the daily GRIB2 pipeline runs and
# uploads release assets either way, but the source is only advertised in
# tide-current-index.json once this is True. While False, this collector
# emits an empty source list ([]), which generate_index.py accepts as
# "nothing to add" — flip to True to publish once the release assets have
# been validated in production.
PUBLISH_TO_CATALOG = False

GITHUB_RELEASE_BASE = "https://github.com/marcelrv/signalk-router-data/releases/download/ofs-currents-latest"

MODELS = {
    "sfbofs": {
        "name": "San Francisco Bay Operational Forecast System",
        "description": "Surface current forecasts for San Francisco Bay.",
        "cycles": ["03", "09", "15", "21"],
        "forecast_hours": 48,
        "forecast_step_hours": 1,
        # f000 exists for this model, but we start at hour 1 regardless for
        # consistency with the other hourly models (avoids depending on a
        # borderline nowcast/forecast boundary file).
        "first_forecast_hour": 1,
        "bounds": {"min_lat": 37.4, "max_lat": 38.3, "min_lon": -123.1, "max_lon": -121.6},
    },
    "cbofs": {
        "name": "Chesapeake Bay Operational Forecast System",
        "description": "Surface current forecasts for Chesapeake Bay.",
        "cycles": ["00", "06", "12", "18"],
        "forecast_hours": 48,
        "forecast_step_hours": 1,
        # f000 does not exist for CBOFS — files start at f001.
        "first_forecast_hour": 1,
        "bounds": {"min_lat": 36.1, "max_lat": 39.7, "min_lon": -77.4, "max_lon": -74.7},
    },
    "ngofs2": {
        "name": "Northern Gulf Of Mexico Operational Forecast System",
        "description": "Surface current forecasts for the northern Gulf of Mexico.",
        "cycles": ["03", "09", "15", "21"],
        "forecast_hours": 48,
        "forecast_step_hours": 3,
        "first_forecast_hour": 3,
        "bounds": {"min_lat": 21.7, "max_lat": 30.9, "min_lon": -97.9, "max_lon": -85.7},
    },
    "sscofs": {
        "name": "Salish Sea and Columbia River Operational Forecast System",
        "description": "Surface current forecasts for the Salish Sea (Puget Sound, Strait of "
                       "Juan de Fuca) and the Columbia River, extending along the Washington "
                       "and Oregon coast.",
        "cycles": ["03", "09", "15", "21"],
        "forecast_hours": 72,
        "forecast_step_hours": 1,
        "first_forecast_hour": 1,
        "bounds": {"min_lat": 44.3, "max_lat": 52.2, "min_lon": -129.6, "max_lon": -121.9},
    },
    "wcofs": {
        "name": "West Coast Operational Forecast System",
        "description": "Surface current forecasts for the U.S. West Coast.",
        "cycles": ["03"],
        "forecast_hours": 72,
        "forecast_step_hours": 3,
        # f000 does not exist for WCOFS — files start at f003 (3-hourly).
        "first_forecast_hour": 3,
        "bounds": {"min_lat": 18.4, "max_lat": 55.8, "min_lon": -145.4, "max_lon": -112.0},
    },
}


def _polygon_from_bounds(b: dict) -> dict:
    return {"type": "Polygon", "coordinates": [[
        [b["min_lon"], b["min_lat"]], [b["max_lon"], b["min_lat"]],
        [b["max_lon"], b["max_lat"]], [b["min_lon"], b["max_lat"]],
        [b["min_lon"], b["min_lat"]],
    ]]}


def _bbox_of_polygons(poly_coords: list) -> dict:
    lons = [pt[0] for poly in poly_coords for ring in poly for pt in ring]
    lats = [pt[1] for poly in poly_coords for ring in poly for pt in ring]
    return {"min_lat": min(lats) if lats else 0, "min_lon": min(lons) if lons else 0,
            "max_lat": max(lats) if lats else 0, "max_lon": max(lons) if lons else 0}


def main() -> None:
    if not PUBLISH_TO_CATALOG:
        json.dump([], sys.stdout)
        print()
        return

    all_poly_coords = []
    files_entries = []

    for mid, m in MODELS.items():
        b = m["bounds"]
        poly = _polygon_from_bounds(b)
        all_poly_coords.append(poly["coordinates"])
        files_entries.append({
            "region_id": mid,
            "name": m["name"],
            "description": m["description"],
            "boundary_geometry": poly,
            "type": "forecast",
            "url_template": f"{GITHUB_RELEASE_BASE}/{mid}_currents.grb2",
            # Each GRIB2 file bundles every forecast hour as separate
            # messages (no {hour:03d} placeholder in url_template above) —
            # a single-element array signals "one file, not one per hour"
            # (see specs/tide-current-catalog.md §3.3 and the BSH nowcast
            # entries in bsh_currents.py for the same convention).
            "forecast_hours": [0],
            "cycle_hours": m["cycles"],
        })

    source = {
        "id": "nos_ofs",
        "source": "noaa",
        "type": "grib2",
        "name": "Surface Current Forecasts — US Waters (NOAA OFS)",
        "description": "Gridded surface current forecasts (tidal + weather + river forcing) for "
                       "US waters, extracted and re-encoded from official NOAA NOS Operational "
                       "Forecast System model guidance by signalk-router-data scripts "
                       "(https://github.com/marcelrv/signalk-router-data). NOAA data is public "
                       "domain (U.S. Government work); this repackaging is NOT an official NOAA "
                       "product and is not endorsed by NOAA.",
        "contributor": "NOAA National Ocean Service (NOS)",
        "url": "https://tidesandcurrents.noaa.gov/ofs/",
        "tags": ["grib2", "regional", "gridded", "forecast", "noaa", "ocean-currents", "daily"],
        "region": {
            "name": "U.S. Coastal Waters",
            "bounding_box": _bbox_of_polygons(all_poly_coords) if all_poly_coords else {},
            "boundary_geometry": {"type": "MultiPolygon", "coordinates": all_poly_coords},
        },
        "update_check": {"method": "expiry", "max_age_hours": 24, "last_checked": ""},
        "files": files_entries,
    }

    json.dump(source, sys.stdout, indent=2)
    print()


if __name__ == "__main__":
    main()
